In [37]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [38]:
tf.__version__

'2.1.0'

In [39]:
hello = tf.constant("Hello")

In [40]:
world = tf.constant("World")

In [41]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [43]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [44]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [45]:
print(result)

b'HelloWorld'


In [47]:
var1 = tf.constant(10)
var2 = tf.constant(30)

In [48]:
var1 + var2

<tf.Tensor 'add_7:0' shape=() dtype=int32>

In [50]:
with tf.Session() as sess:
    result = sess.run(var1+var2)

In [51]:
print(result)

40


In [53]:
const = tf.constant(10)

In [57]:
mat_1 = tf.fill((5, 5), 10)

In [58]:
zeros = tf.zeros((5,5))

In [59]:
ones = tf.ones((5, 5))

In [62]:
randn = tf.random_normal((4, 4), mean = 0, stddev = 1.0)

In [63]:
randm = tf.random_uniform((4, 4), minval=0, maxval=1)

In [68]:
myops = [const, mat_1, zeros, ones, randn, randm]

In [71]:
sess = tf.InteractiveSession()

In [73]:
for op in myops:
    #print(sess.run(op))
    print(op.eval())
    print("\n")

10


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[ 1.8844662  -1.6913472  -0.9502419  -0.54275835]
 [ 0.21675687 -1.5986222  -0.548637    0.52807355]
 [-0.29385468  0.05422217  0.3824426   0.3467985 ]
 [ 0.3016209   0.6918061   1.1915685   0.64130604]]


[[0.3051356  0.08163702 0.36003423 0.71542346]
 [0.36700916 0.6140722  0.34175885 0.5269755 ]
 [0.24832392 0.22953069 0.3388995  0.0738008 ]
 [0.9757737  0.40730357 0.36632133 0.5315641 ]]




In [75]:
a = tf.constant([[1,2], [3, 4]])

In [77]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [78]:
b = tf.constant([[10], [100]])

In [79]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [80]:
result = tf.matmul(a, b)

In [81]:
sess.run(result)

array([[210],
       [430]])

In [93]:
var1 = tf.constant(10)

In [94]:
var2 = tf.constant(20)

In [95]:
var3 = var1 + var2

In [96]:
with tf.Session() as sess:
    result = sess.run(var3)

In [97]:
print(result)

30


In [99]:
print(var3)

Tensor("add_11:0", shape=(), dtype=int32)


In [100]:
print(tf.get_default_graph())

In [101]:
g = tf.Graph()
print(g)

In [102]:
g_1 = tf.get_default_graph()

In [103]:
print(g_1)

In [104]:
g_2 = tf.Graph()
print(g_2)

In [105]:
with g_2.as_default():
    print(g_2 is tf.get_default_graph())

True


In [106]:
print(g_2 is tf.get_default_graph())

False


In [109]:
sess = tf.InteractiveSession()

In [110]:
my_tensor = tf.random_uniform((5,5), 0, 2)

In [111]:
my_tensor

<tf.Tensor 'random_uniform_1:0' shape=(5, 5) dtype=float32>

In [112]:
var1 = tf.Variable(initial_value=my_tensor)

In [113]:
print(var1)

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32_ref>


In [116]:
#sess.run(var1)
init = tf.global_variables_initializer()

In [117]:
sess.run(init)

In [118]:
sess.run(var1)

array([[0.5118563 , 0.7649174 , 0.34533238, 1.9294338 , 1.0660138 ],
       [1.0267124 , 1.2246847 , 0.18447518, 0.81874895, 1.5064592 ],
       [1.7384009 , 0.98250365, 1.7482731 , 1.2940676 , 1.4908314 ],
       [1.6976213 , 1.3092272 , 0.801708  , 1.3930206 , 0.28527355],
       [1.6649284 , 1.6539907 , 1.0448248 , 1.6365662 , 1.4516377 ]],
      dtype=float32)

In [120]:
pH1 = tf.placeholder(tf.float32, shape=(None, 4))

In [121]:
pH2 = tf.placeholder(tf.float32)